# fly.toml app configuration file generated for adg-home on 2024-02-14T13:31:13+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "adg-home"
primary_region = "cdg"

[build]

[[mounts]]
  source = "adg_data"
  destination = "/data"

# http/https admin panel access, dns over https
[http_service]
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

# plain dns
[[services]]
  internal_port = 53
  protocol = "udp"
  [[services.ports]]
    port = 53

[[services]]
  internal_port = 53
  protocol = "tcp"
  [[services.ports]]
    port = 53

# dns over tls
[[services]]
  internal_port = 853
  protocol = "tcp"
  [[services.ports]]
    port = 853
    handlers = ["tls"]

# dns over quic
[[services]]
  protocol = "udp"
  internal_port = 853
  [[services.ports]]
    port = 853
