name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [AdGuardHome.yaml, Dockerfile]

jobs:
  deployment:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}